"""empty message

Revision ID: 4a2d13fd36b7
Revises: 53b3f6798130
Create Date: 2023-04-09 09:29:29.805745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2d13fd36b7'
down_revision = '53b3f6798130'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('phone_number', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
